# Generated by Django 5.2.3 on 2025-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular'),
        ),
    ]
