# Generated by Django 5.2.2 on 2025-06-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercambio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('solicitud_enviada', 'Solicitud enviada'), ('solicitud_aceptada', 'Solicitud aceptada'), ('solicitud_rechazada', 'Solicitud rechazada'), ('libro_intercambiado', 'Libro intercambiado')], max_length=50)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambio.solicitudintercambio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
